### PR TITLE
Better algorithm for RMS measurement

### PR DESCRIPTION
**Pull request by ziutek**
I've implemented a better algorithm for RMS measurement. Tested with a sine and a sawtooth waveform.

It works well if the averaged waveform has a lot of periods but it's weakening as the number of periods decrease because of unavoidable head/tail incomplete periods.

The algorithm can be improved by adding some kind of averaging window.

I've changed the version number from 0.005 to 0.006 mainly to confirm the update on my scope was successful.

### CODE REVIEW

**Review by pecostm32 — APPROVED** [review]
Thanks for this.

It is going in the repository.

**Comment by pecostm32** [comment]
Done

**Review by pecostm32 — COMMENTED** [review]
Merged

**Comment by pecostm32** [comment]
I don't know what I did wrong or missed, but the changes don't show up. Not an experienced github user.

Does it require action from your part?

**Comment by pecostm32** [comment]
Never mind finally found the button to get it done.

**Comment by ziutek** [comment]
:)

**Pull request merged**
